// <auto-generated />
using System;
using EvaGest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvaGest.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20260905121102_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("EvaGest.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<int>("DuradaMin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("durada_min");

                    b.Property<string>("Estat")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("estat");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora");

                    b.Property<string>("NomConvidat")
                        .HasColumnType("TEXT")
                        .HasColumnName("nom_convidat");

                    b.Property<string>("Observacions")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacions");

                    b.Property<int?>("ServeiId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("servei_id");

                    b.Property<string>("TelefonConvidat")
                        .HasColumnType("TEXT")
                        .HasColumnName("telefon_convidat");

                    b.Property<int?>("TreballadoraId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("treballadora_id");

                    b.HasKey("Id")
                        .HasName("pk_cites");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_cites_client_id");

                    b.HasIndex("ServeiId")
                        .HasDatabaseName("ix_cites_servei_id");

                    b.HasIndex("TreballadoraId")
                        .HasDatabaseName("ix_cites_treballadora_id");

                    b.HasIndex("Data", "Hora")
                        .HasDatabaseName("ix_cites_data_hora");

                    b.ToTable("cites", null, t =>
                        {
                            t.HasCheckConstraint("ck_cites_client_xor", "(client_id IS NOT NULL AND nom_convidat IS NULL) OR (client_id IS NULL AND nom_convidat IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("EvaGest.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Adormit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("adormit");

                    b.Property<string>("ClientKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_key");

                    b.Property<string>("Correu")
                        .HasColumnType("TEXT")
                        .HasColumnName("correu");

                    b.Property<DateOnly?>("DataNaixement")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_naixement");

                    b.Property<string>("Mobil")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mobil");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom");

                    b.Property<string>("Observacions")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacions");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("ClientKey")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_client_key");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.ConfiguracioItem", b =>
                {
                    b.Property<string>("Clau")
                        .HasColumnType("TEXT")
                        .HasColumnName("clau");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("valor");

                    b.HasKey("Clau")
                        .HasName("pk_configuracio");

                    b.ToTable("configuracio", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.DiaTancat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("Motiu")
                        .HasColumnType("TEXT")
                        .HasColumnName("motiu");

                    b.HasKey("Id")
                        .HasName("pk_dies_tancats");

                    b.HasIndex("Data")
                        .IsUnique()
                        .HasDatabaseName("ix_dies_tancats_data");

                    b.ToTable("dies_tancats", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.HorariBarberia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DiaSetmana")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dia_setmana");

                    b.Property<TimeOnly>("HoraObertura")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_obertura");

                    b.Property<TimeOnly>("HoraTancament")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_tancament");

                    b.HasKey("Id")
                        .HasName("pk_horari_barberia");

                    b.ToTable("horari_barberia", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.HorariTreballadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DiaSetmana")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dia_setmana");

                    b.Property<TimeOnly>("HoraFi")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_fi");

                    b.Property<TimeOnly>("HoraInici")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_inici");

                    b.Property<int>("TreballadoraId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("treballadora_id");

                    b.HasKey("Id")
                        .HasName("pk_horaris_treballadora");

                    b.HasIndex("TreballadoraId")
                        .HasDatabaseName("ix_horaris_treballadora_treballadora_id");

                    b.ToTable("horaris_treballadora", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.MetodePagament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Actiu")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actiu");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("pk_metodes_pagament");

                    b.HasIndex("Nom")
                        .IsUnique()
                        .HasDatabaseName("ix_metodes_pagament_nom");

                    b.ToTable("metodes_pagament", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.MovimentCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BaseCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_cents");

                    b.Property<string>("Concepte")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("concepte");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<int>("ImportCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("import_cents");

                    b.Property<int?>("IvaBp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iva_bp");

                    b.Property<int?>("IvaCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iva_cents");

                    b.Property<int>("MetodePagamentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("metode_pagament_id");

                    b.Property<string>("Observacions")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacions");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipus");

                    b.HasKey("Id")
                        .HasName("pk_moviments_caixa");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_moviments_caixa_data");

                    b.HasIndex("MetodePagamentId")
                        .HasDatabaseName("ix_moviments_caixa_metode_pagament_id");

                    b.ToTable("moviments_caixa", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.Producte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Actiu")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actiu");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT")
                        .HasColumnName("categoria");

                    b.Property<int>("IvaBp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iva_bp");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom");

                    b.Property<int>("PreuCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preu_cents");

                    b.HasKey("Id")
                        .HasName("pk_productes");

                    b.ToTable("productes", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.Servei", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Actiu")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actiu");

                    b.Property<int?>("DuradaMin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("durada_min");

                    b.Property<int>("IvaBp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iva_bp");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom");

                    b.Property<int>("PreuCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preu_cents");

                    b.HasKey("Id")
                        .HasName("pk_serveis");

                    b.ToTable("serveis", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.Treballadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Actiu")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actiu");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("pk_treballadores");

                    b.ToTable("treballadores", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BaseCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_cents");

                    b.Property<int?>("CitaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cita_id");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("Estat")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("estat");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora");

                    b.Property<int>("IvaCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iva_cents");

                    b.Property<string>("IvaMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("iva_mode");

                    b.Property<int>("MetodePagamentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("metode_pagament_id");

                    b.Property<string>("NomConvidat")
                        .HasColumnType("TEXT")
                        .HasColumnName("nom_convidat");

                    b.Property<string>("Observacions")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacions");

                    b.Property<string>("TelefonConvidat")
                        .HasColumnType("TEXT")
                        .HasColumnName("telefon_convidat");

                    b.Property<int>("TotalCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_cents");

                    b.Property<int?>("TreballadoraId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("treballadora_id");

                    b.HasKey("Id")
                        .HasName("pk_vendes");

                    b.HasIndex("CitaId")
                        .IsUnique()
                        .HasDatabaseName("ix_vendes_cita_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_vendes_client_id");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_vendes_data");

                    b.HasIndex("Estat")
                        .HasDatabaseName("ix_vendes_estat");

                    b.HasIndex("MetodePagamentId")
                        .HasDatabaseName("ix_vendes_metode_pagament_id");

                    b.HasIndex("TreballadoraId")
                        .HasDatabaseName("ix_vendes_treballadora_id");

                    b.ToTable("vendes", null, t =>
                        {
                            t.HasCheckConstraint("ck_vendes_client_xor", "(client_id IS NOT NULL AND nom_convidat IS NULL) OR (client_id IS NULL AND nom_convidat IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("EvaGest.Models.VendaDesglossament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BaseCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_cents");

                    b.Property<int>("IvaBp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iva_bp");

                    b.Property<int>("IvaCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iva_cents");

                    b.Property<int>("TotalCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_cents");

                    b.Property<int>("VendaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_venda_desglossaments");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_venda_desglossaments_venda_id");

                    b.ToTable("venda_desglossaments", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.VendaLinia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Descripcio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcio");

                    b.Property<int>("ImportCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("import_cents");

                    b.Property<int>("IvaBp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iva_bp");

                    b.Property<int>("PreuUnitariCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preu_unitari_cents");

                    b.Property<int?>("ProducteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("producte_id");

                    b.Property<int>("Quantitat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantitat");

                    b.Property<int?>("ServeiId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("servei_id");

                    b.Property<int>("VendaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_venda_linies");

                    b.HasIndex("ProducteId")
                        .HasDatabaseName("ix_venda_linies_producte_id");

                    b.HasIndex("ServeiId")
                        .HasDatabaseName("ix_venda_linies_servei_id");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_venda_linies_venda_id");

                    b.ToTable("venda_linies", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.Cita", b =>
                {
                    b.HasOne("EvaGest.Models.Client", "Client")
                        .WithMany("Cites")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_cites_clients_client_id");

                    b.HasOne("EvaGest.Models.Servei", "Servei")
                        .WithMany()
                        .HasForeignKey("ServeiId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cites_serveis_servei_id");

                    b.HasOne("EvaGest.Models.Treballadora", "Treballadora")
                        .WithMany("Cites")
                        .HasForeignKey("TreballadoraId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cites_treballadores_treballadora_id");

                    b.Navigation("Client");

                    b.Navigation("Servei");

                    b.Navigation("Treballadora");
                });

            modelBuilder.Entity("EvaGest.Models.HorariTreballadora", b =>
                {
                    b.HasOne("EvaGest.Models.Treballadora", "Treballadora")
                        .WithMany("Horaris")
                        .HasForeignKey("TreballadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_horaris_treballadora_treballadores_treballadora_id");

                    b.Navigation("Treballadora");
                });

            modelBuilder.Entity("EvaGest.Models.MovimentCaixa", b =>
                {
                    b.HasOne("EvaGest.Models.MetodePagament", "MetodePagament")
                        .WithMany()
                        .HasForeignKey("MetodePagamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moviments_caixa_metodes_pagament_metode_pagament_id");

                    b.Navigation("MetodePagament");
                });

            modelBuilder.Entity("EvaGest.Models.Venda", b =>
                {
                    b.HasOne("EvaGest.Models.Cita", "Cita")
                        .WithOne("Venda")
                        .HasForeignKey("EvaGest.Models.Venda", "CitaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_vendes_cites_cita_id");

                    b.HasOne("EvaGest.Models.Client", "Client")
                        .WithMany("Vendes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_vendes_clients_client_id");

                    b.HasOne("EvaGest.Models.MetodePagament", "MetodePagament")
                        .WithMany()
                        .HasForeignKey("MetodePagamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendes_metodes_pagament_metode_pagament_id");

                    b.HasOne("EvaGest.Models.Treballadora", "Treballadora")
                        .WithMany("Vendes")
                        .HasForeignKey("TreballadoraId")
                        .HasConstraintName("fk_vendes_treballadores_treballadora_id");

                    b.Navigation("Cita");

                    b.Navigation("Client");

                    b.Navigation("MetodePagament");

                    b.Navigation("Treballadora");
                });

            modelBuilder.Entity("EvaGest.Models.VendaDesglossament", b =>
                {
                    b.HasOne("EvaGest.Models.Venda", "Venda")
                        .WithMany("Desglossaments")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_venda_desglossaments_vendes_venda_id");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("EvaGest.Models.VendaLinia", b =>
                {
                    b.HasOne("EvaGest.Models.Producte", "Producte")
                        .WithMany()
                        .HasForeignKey("ProducteId")
                        .HasConstraintName("fk_venda_linies_productes_producte_id");

                    b.HasOne("EvaGest.Models.Servei", "Servei")
                        .WithMany()
                        .HasForeignKey("ServeiId")
                        .HasConstraintName("fk_venda_linies_serveis_servei_id");

                    b.HasOne("EvaGest.Models.Venda", "Venda")
                        .WithMany("Linies")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_venda_linies_vendes_venda_id");

                    b.Navigation("Producte");

                    b.Navigation("Servei");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("EvaGest.Models.Cita", b =>
                {
                    b.Navigation("Venda");
                });

            modelBuilder.Entity("EvaGest.Models.Client", b =>
                {
                    b.Navigation("Cites");

                    b.Navigation("Vendes");
                });

            modelBuilder.Entity("EvaGest.Models.Treballadora", b =>
                {
                    b.Navigation("Cites");

                    b.Navigation("Horaris");

                    b.Navigation("Vendes");
                });

            modelBuilder.Entity("EvaGest.Models.Venda", b =>
                {
                    b.Navigation("Desglossaments");

                    b.Navigation("Linies");
                });
#pragma warning restore 612, 618
        }
    }
}
