// <auto-generated />
using System;
using EvaGest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvaGest.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20260917204335_AddExpenseCategoryAndCashMovementLinks")]
    partial class AddExpenseCategoryAndCashMovementLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("EvaGest.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int>("DurationMin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_min");

                    b.Property<string>("GuestName")
                        .HasColumnType("TEXT")
                        .HasColumnName("guest_name");

                    b.Property<string>("GuestPhone")
                        .HasColumnType("TEXT")
                        .HasColumnName("guest_phone");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_appointments_client_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_appointments_service_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_appointments_worker_id");

                    b.HasIndex("Date", "Time")
                        .HasDatabaseName("ix_appointments_date_time");

                    b.ToTable("appointments", null, t =>
                        {
                            t.HasCheckConstraint("ck_appointments_client_xor", "(client_id IS NOT NULL AND guest_name IS NULL) OR (client_id IS NULL AND guest_name IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("EvaGest.Models.CashMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AmountCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_cents");

                    b.Property<int?>("BaseCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_cents");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("concept");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<int?>("VatBp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vat_bp");

                    b.Property<int?>("VatCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vat_cents");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_cash_movements");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_cash_movements_category_id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_cash_movements_date");

                    b.HasIndex("PaymentMethodId")
                        .HasDatabaseName("ix_cash_movements_payment_method_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_cash_movements_worker_id");

                    b.ToTable("cash_movements", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Asleep")
                        .HasColumnType("INTEGER")
                        .HasColumnName("asleep");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<string>("ClientKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_key");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("ClientKey")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_client_key");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.ClosedDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_closed_days");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("ix_closed_days_date");

                    b.ToTable("closed_days", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_expense_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_expense_categories_name");

                    b.ToTable("expense_categories", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_payment_methods");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_methods_name");

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PriceCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price_cents");

                    b.Property<int>("VatBp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vat_bp");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("appointment_id");

                    b.Property<int>("BaseCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_cents");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("GuestName")
                        .HasColumnType("TEXT")
                        .HasColumnName("guest_name");

                    b.Property<string>("GuestPhone")
                        .HasColumnType("TEXT")
                        .HasColumnName("guest_phone");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<int>("TotalCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_cents");

                    b.Property<int>("VatCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vat_cents");

                    b.Property<string>("VatMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vat_mode");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_appointment_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_sales_client_id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_sales_date");

                    b.HasIndex("PaymentMethodId")
                        .HasDatabaseName("ix_sales_payment_method_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sales_status");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_sales_worker_id");

                    b.ToTable("sales", null, t =>
                        {
                            t.HasCheckConstraint("ck_sales_client_xor", "(client_id IS NOT NULL AND guest_name IS NULL) OR (client_id IS NULL AND guest_name IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("EvaGest.Models.SaleBreakdown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BaseCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_cents");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sale_id");

                    b.Property<int>("TotalCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_cents");

                    b.Property<int>("VatBp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vat_bp");

                    b.Property<int>("VatCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vat_cents");

                    b.HasKey("Id")
                        .HasName("pk_sale_breakdowns");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_breakdowns_sale_id");

                    b.ToTable("sale_breakdowns", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.SaleLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AmountCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_cents");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sale_id");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_id");

                    b.Property<int>("UnitPriceCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_price_cents");

                    b.Property<int>("VatBp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vat_bp");

                    b.HasKey("Id")
                        .HasName("pk_sale_lines");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sale_lines_product_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_lines_sale_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_sale_lines_service_id");

                    b.ToTable("sale_lines", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<int?>("DurationMin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_min");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PriceCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price_cents");

                    b.Property<int>("VatBp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vat_bp");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.SettingItem", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.ShopSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("closing_time");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("opening_time");

                    b.Property<string>("Weekday")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("weekday");

                    b.HasKey("Id")
                        .HasName("pk_shop_schedule");

                    b.ToTable("shop_schedule", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_workers");

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.WorkerSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<string>("Weekday")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("weekday");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_worker_schedules");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_worker_schedules_worker_id");

                    b.ToTable("worker_schedules", (string)null);
                });

            modelBuilder.Entity("EvaGest.Models.Appointment", b =>
                {
                    b.HasOne("EvaGest.Models.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_appointments_clients_client_id");

                    b.HasOne("EvaGest.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_appointments_services_service_id");

                    b.HasOne("EvaGest.Models.Worker", "Worker")
                        .WithMany("Appointments")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_appointments_workers_worker_id");

                    b.Navigation("Client");

                    b.Navigation("Service");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("EvaGest.Models.CashMovement", b =>
                {
                    b.HasOne("EvaGest.Models.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cash_movements_expense_categories_category_id");

                    b.HasOne("EvaGest.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cash_movements_payment_methods_payment_method_id");

                    b.HasOne("EvaGest.Models.Worker", "Worker")
                        .WithMany("CashMovements")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cash_movements_workers_worker_id");

                    b.Navigation("Category");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("EvaGest.Models.Sale", b =>
                {
                    b.HasOne("EvaGest.Models.Appointment", "Appointment")
                        .WithOne("Sale")
                        .HasForeignKey("EvaGest.Models.Sale", "AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sales_appointments_appointment_id");

                    b.HasOne("EvaGest.Models.Client", "Client")
                        .WithMany("Sales")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_sales_clients_client_id");

                    b.HasOne("EvaGest.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_payment_methods_payment_method_id");

                    b.HasOne("EvaGest.Models.Worker", "Worker")
                        .WithMany("Sales")
                        .HasForeignKey("WorkerId")
                        .HasConstraintName("fk_sales_workers_worker_id");

                    b.Navigation("Appointment");

                    b.Navigation("Client");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("EvaGest.Models.SaleBreakdown", b =>
                {
                    b.HasOne("EvaGest.Models.Sale", "Sale")
                        .WithMany("Breakdowns")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_breakdowns_sales_sale_id");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("EvaGest.Models.SaleLine", b =>
                {
                    b.HasOne("EvaGest.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_sale_lines_products_product_id");

                    b.HasOne("EvaGest.Models.Sale", "Sale")
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_lines_sales_sale_id");

                    b.HasOne("EvaGest.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("fk_sale_lines_services_service_id");

                    b.Navigation("Product");

                    b.Navigation("Sale");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("EvaGest.Models.WorkerSchedule", b =>
                {
                    b.HasOne("EvaGest.Models.Worker", "Worker")
                        .WithMany("Schedules")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_schedules_workers_worker_id");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("EvaGest.Models.Appointment", b =>
                {
                    b.Navigation("Sale");
                });

            modelBuilder.Entity("EvaGest.Models.Client", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("EvaGest.Models.Sale", b =>
                {
                    b.Navigation("Breakdowns");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("EvaGest.Models.Worker", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CashMovements");

                    b.Navigation("Sales");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
